# Generated by Django 4.0 on 2024-06-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(blank=True, max_length=256)),
                ('project_id', models.IntegerField(blank=True)),
                ('picture_data', models.BinaryField(blank=True)),
                ('new_data', models.IntegerField()),
            ],
            options={
                'db_table': 'picture',
            },
        ),
    ]
