# Generated by Django 4.0 on 2024-06-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='new_data',
        ),
        migrations.AddField(
            model_name='picture',
            name='state',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
